#!/bin/sh
# Script to create a PyQT deb package using fpm
#
# This script will create a folder structure that will be used as input
# for the fpm command and copy into it all the distributable files generated by
# pyinstaller. 
# We will create a folder with the same structure Linux systems expects:
#  - /opt for our executable and associated files (a.k.a our dist/ folder)
#  - /usr/share/applications (for the .desktop file)
#  - /usr/share/icons/hicolor/scalable/apps for our svg icons (only svg in scalable folder)
#
# More info:
#  - https://www.pythonguis.com/tutorials/packaging-pyqt5-applications-linux-pyinstaller/
#  - https://fpm.readthedocs.io/en/latest/packages/dir.html#dir-local-files
#
# Create folders
[ -e package ] && rm -r package
mkdir -p package/opt
mkdir -p package/usr/share/applications
mkdir -p package/usr/share/icons/hicolor/scalable/apps

# Build the project
[ -e build ] && rm -r build
[ -e dist ] && rm -r dist
pyinstaller ./packaging/linux/hello-world-linux.spec

# Copy files
cp -r dist/hello-world package/opt/hello-world
cp ./src/media/icons/icon.svg package/usr/share/icons/hicolor/scalable/apps/hello-world.svg
cp ./packaging/linux/hello-world.desktop package/usr/share/applications

# Change permissions
# Packages retain the permissions of installed files from when they were packaged,
# but will be installed by root. In order for ordinary users to be able to run the
# application, we need to change the permissions.
find package/opt/hello-world -type f -exec chmod 644 -- {} +
find package/opt/hello-world -type d -exec chmod 755 -- {} +
find package/usr/share -type f -exec chmod 644 -- {} +
chmod +x package/opt/hello-world/hello-world

# Create the deb package
[ -e hello-world.deb ] && rm hello-world.deb
fpm -C package -s dir -t deb -n "hello-world" -v 0.1.0 -p hello-world.deb
