name: Build DMG
'on':
  push:
    branches:
      - "main"

jobs:
  on-push-main:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Dependencies
        run: |
          pip3 install pyqt6 pyinstaller
          brew install create-dmg
      - name: Build and notarize the dmg file
        env:
          MAC_P12_BASE64_CERTIFICATE: ${{ secrets.MAC_P12_BASE64_CERTIFICATE }}
          MAC_P12_PASSWORD: ${{ secrets.MAC_P12_PASSWORD }}
          MAC_TEAM_ID: ${{ secrets.MAC_TEAM_ID }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          MAC_APPLE_ID: ${{ secrets.MAC_APPLE_ID }}
          MAC_APP_SPECIFIC_PASSWORD: ${{ secrets.MAC_APP_SPECIFIC_PASSWORD }}
        run: |
          ./packaging/macos/build-dmg.sh
      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: distribution-files-macos
          path: |
            HelloWorld.dmg
          retention-days: 14
